{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "d8e3ec966fc724d3011c6aa2a3862d2eaa1f331e"
}