{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "f1875b87a0e8e2a4fc364c77b1ca3e808e430d92"
}