{
  "MIME": "application/x-wine-extension-ini",
  "inode_type": "REG",
  "magic_type": "Generic INItialization configuration [MaxLen ( 256 )]\\015",
  "mode": "-rwxrwxrwx",
  "sha1": "1d425bb713b8467d470ed97e0a614c54fd42e5bb"
}