{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "b7cf0a606f23a27af8a297582761a533c56f0625"
}