{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "43af18742b4db688b0fb44961a80b51d5a263185"
}