{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "bbc9d0b89aa4c2be98182f80321a741e25006de8"
}