{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "543d55f442c2fcce62051fad9ccc55742f8945ae"
}