{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, Little-endian UTF-16 Unicode text, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "5d2254ca7da8a1642edc53fb811c8bccb095d313"
}