{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "bffb8fb12d83d16415dcbf89e5cc7b260faa531e"
}