{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "356be6e2a1b4ab6ad619f024846be0b8069bd6e5"
}