{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "bd6edba36964d79a2f869d1e2563f600ed960dee"
}