{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "0767803985500be682fd8076f38c7c1c93620d0e"
}