{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "f4503b7604ffe9a7de991ba8cd47f45d486c336d"
}