{
  "MIME": "text/x-makefile",
  "inode_type": "REG",
  "magic_type": "makefile script, ASCII text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "ee3f50d0f5aef8f91eeee9d1c8a6c84c3c751f4e"
}