{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "e0e60e10d09a0eb7853ce2abec07defcb5af1087"
}