{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, ASCII text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "426eb98d3ee33a11cba2f2a9f9bfc5d666eb4368"
}