{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, Little-endian UTF-16 Unicode text, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "bead656f1a1888c713d70470aa00a316b309dd42"
}