{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, ASCII text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "1b397076633203621e14684dd2a68d07bfc7274b"
}