{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "55eb3c78032012a3d7bf48760fd5cefcf3fe8761"
}