{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "a632bb5b3cd2d9235fffa9bf759aebbffad63726"
}