{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, Little-endian UTF-16 Unicode text, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "249214579cc9a82197f47ce711d60ee1ebfbaeeb"
}