{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "5ef3bb99f594d9456170926ada0813e5df1761f3"
}