{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "66365dffe0edad0963ab1434846cfb7068ede0c5"
}