{
  "MIME": "text/x-c++",
  "inode_type": "REG",
  "magic_type": "C++ source, Little-endian UTF-16 Unicode text, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "11fb5cc383c3711f5cca474eb67a0c0a41b08ce0"
}