{
  "MIME": "application/x-wine-extension-ini",
  "inode_type": "REG",
  "magic_type": "Generic INItialization configuration [MaxLen ( 256 )]\\015",
  "mode": "-rwxrwxrwx",
  "sha1": "6e1aa756c430691e4c36705636d8d8b217383b45"
}