{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with very long lines, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "619366362c6554eacbc2f94d831681d7d73d7008"
}