{
  "MIME": "application/x-wine-extension-ini",
  "inode_type": "REG",
  "magic_type": "Generic INItialization configuration [     read]\\015",
  "mode": "-rwxrwxrwx",
  "sha1": "64cc1ab6693e4f4fbbb641ceed8109cfaa90f24f"
}