{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "f049cc25dad5d98f8d9cfb4a3eb04a653b9047a5"
}