{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "63764cecd72db342f789500d74f1c2fcda6c605b"
}