{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "eb9c5e7b552e5df5cd14cfab496e58510c076218"
}