{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "05b52fc3e8fe88fea4b8f4df1d240973e9796abf"
}