{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, ASCII text, with very long lines, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "41e0606a77c403b1acd5744a4ef11c70fae986de"
}