{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "e2e965a8a5d23adf6d5f89f67a043d965fce90d8"
}