{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "ce97522f474ebed2f7ed5ca5a29af1ee0d2236eb"
}