{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF, LF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "4a0bfca5582232d4bf8bd1e642038604b48bfc88"
}