{
  "MIME": "text/plain",
  "inode_type": "REG",
  "magic_type": "Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "3c773ab8282a570b9f34a9b79d7b6fa56d7d64cd"
}