{
  "MIME": "text/x-c",
  "inode_type": "REG",
  "magic_type": "C source, Little-endian UTF-16 Unicode text, with CRLF line terminators",
  "mode": "-rwxrwxrwx",
  "sha1": "677b1a46b6f64fe02d90d4e9884a783149989b7f"
}